version: '3'
services:

  turn-data-collector:
    build:
      context: .
    image: haugene/turn-data-collector
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8080:8080

  db:
    image: postgres
    volumes:
      - turndata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432

volumes:
  turndata:
