server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/particle
    username: postgres
    password: mysecretpassword
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

logging:
  level:
    root: info
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG

camel:
  pubsub:
    auth:
      serviceAccount: service-account
      serviceAccountKey: secret-key

---
spring:
  profiles: docker
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: mysecretpassword